### ISSUE TITLE
page is wider than browser in Win Chrome

### ISSUE THREAD

**Issue by connerk** [rogue-hack-lab/rhl-new#8] opened 2017-04-12 05:23 UTC
appears to be related to slideout

**Comment by Pater1** [comment] 2017-04-13 20:48
Should this be marked solved? Looking now at the (recently pulled/compiled) page on Win Chrome, and it's the proper width...

16:9, 1440p monitor if maybe the issue is screen-size related.

**Comment by connerk** [comment] 2017-04-13 20:54
I got the same issue in Windows and Linux using Chrome, with the screen full size or reduced. I'm still getting it right now at http://roguehacklab.com/rhl-new/

**Comment by Pater1** [comment] 2017-04-13 21:12
Hmm... I can't seem to replicate the bug on my laptop. Tried maximized, full-screen windowed, half-screen (vertically split) windowed, and 1/4-screen windowed using the link you provided. Tested @1440p, 1080p, and 720p on my laptop (Win 10 edu, Chrome build 57.0.2987.133).

Any tips on replicating the bug?

**Comment by connerk** [comment] 2017-04-13 21:13
@Pater1 when you load you don't get a horizontal scroll bar at all?

**Comment by Pater1** [comment] 2017-04-13 21:14
One pops up, but it doesn't scroll any (noticeable) distance.

**Comment by connerk** [comment] 2017-04-13 21:15
yeah, it shouldn't be there at all. a horizontal scroll bar will only show up if the page is wider than the browser. you are indeed seeing the bug. it just doesn't bug you ;)

**Comment by Pater1** [comment] 2017-04-13 21:16
*note that the do-nothing scroll bar pops up in Firefox too (only tested 1440p, maximized).

**Comment by Pater1** [comment] 2017-04-13 22:42
Narrowed bug down to hero.html (or a component of). Tested by commenting out the hero.html include in index: 
![capture](https://cloud.githubusercontent.com/assets/4977838/25027211/2fe92d5c-2068-11e7-8f69-1314acd4abec.PNG)

**Comment by Pater1** [comment] 2017-04-13 22:52
Solved the bug, but can't open new pull request while the menu one is open. (Sorry, I forgot to make separate branches...)
![capture](https://cloud.githubusercontent.com/assets/4977838/25027394/9ea9b35a-2069-11e7-981c-bd8f1ae1e05d.PNG)

**Comment by pcunning** [comment] 2017-04-14 04:06
fix merged #20

**Closed by pcunning** 2017-04-14 04:06 UTC
Labels: bug

**Comment by connerk** [comment] 2017-04-14 05:53
Did this break anything in browsers that worked before?
